using HandmadeFinance.Application.Abstractions.Persistence; using HandmadeFinance.Application.Common; using HandmadeFinance.Application.Ledger; using Xunit;
namespace HandmadeFinance.Application.Tests.Ledger;
public sealed class LedgerServiceTests
{
    private readonly FakeRepository _repo=new(); private readonly FakeClock _clock=new(); private LedgerService Service=>new(_repo,_clock); private static LedgerWrite Valid=>new(new DateOnly(2026,9,17),"Order",1,100m,10m,110m);
    [Fact]public async Task Viewer_cannot_create(){var ex=await Assert.ThrowsAsync<AppException>(()=>Service.CreateAsync(EntryKind.INCOME,Valid,new(1,UserRole.VIEWER),default));Assert.Equal(403,ex.Status);}
    [Fact]public async Task Employee_can_create_and_owns_record(){var row=await Service.CreateAsync(EntryKind.INCOME,Valid,new(7,UserRole.EMPLOYEE),default);Assert.Equal(7,row.CreatedBy);Assert.Equal("USD",row.CurrencyCode);}
    [Fact]public async Task Employee_cannot_update_another_users_record(){var row=await Service.CreateAsync(EntryKind.INCOME,Valid,new(7,UserRole.EMPLOYEE),default);var ex=await Assert.ThrowsAsync<AppException>(()=>Service.UpdateAsync(EntryKind.INCOME,row.Id,Valid,new(8,UserRole.EMPLOYEE),default));Assert.Equal(403,ex.Status);}
    [Fact]public async Task Employee_can_update_own_record(){var row=await Service.CreateAsync(EntryKind.INCOME,Valid,new(7,UserRole.EMPLOYEE),default);var changed=await Service.UpdateAsync(EntryKind.INCOME,row.Id,Valid with{Description="Changed"},new(7,UserRole.EMPLOYEE),default);Assert.Equal("Changed",changed.Description);}
    [Fact]public async Task Employee_cannot_delete(){var row=await Service.CreateAsync(EntryKind.EXPENSE,Valid,new(7,UserRole.EMPLOYEE),default);await Assert.ThrowsAsync<AppException>(()=>Service.DeleteAsync(EntryKind.EXPENSE,row.Id,new(7,UserRole.EMPLOYEE),default));}
    [Fact]public async Task Soft_deleted_record_is_not_listed_or_returned(){var row=await Service.CreateAsync(EntryKind.INCOME,Valid,new(1,UserRole.ADMIN),default);await Service.DeleteAsync(EntryKind.INCOME,row.Id,new(1,UserRole.ADMIN),default);var page=await Service.ListAsync(EntryKind.INCOME,new(),default);Assert.Empty(page.Items);await Assert.ThrowsAsync<AppException>(()=>Service.GetAsync(EntryKind.INCOME,row.Id,default));}
    [Fact]public async Task Rejects_inconsistent_tax_total(){var bad=Valid with{AmountAfterTax=109};var ex=await Assert.ThrowsAsync<AppException>(()=>Service.CreateAsync(EntryKind.INCOME,bad,new(1,UserRole.ADMIN),default));Assert.Equal(400,ex.Status);}
    [Fact]public async Task Rejects_invalid_date_range(){await Assert.ThrowsAsync<AppException>(()=>Service.ListAsync(EntryKind.INCOME,new(DateFrom:new(2026,2,2),DateTo:new(2026,1,1)),default));}
    private sealed class FakeClock:IClock{public DateTimeOffset UtcNow=>new(2026,9,17,0,0,0,TimeSpan.Zero);}
    private sealed class FakeRepository:ILedgerRepository{private readonly List<LedgerEntry> rows=[];public Task<LedgerEntry>AddAsync(LedgerEntry e,CancellationToken _){e.Id=rows.Count+1;rows.Add(e);return Task.FromResult(e);}public Task<LedgerEntry?>GetAsync(EntryKind k,long id,CancellationToken _)=>Task.FromResult(rows.SingleOrDefault(x=>x.Kind==k&&x.Id==id));public Task<IReadOnlyList<LedgerEntry>>ListAsync(EntryKind k,CancellationToken _)=>Task.FromResult<IReadOnlyList<LedgerEntry>>(rows.Where(x=>x.Kind==k).ToList());public Task UpdateAsync(LedgerEntry e,CancellationToken _)=>Task.CompletedTask;}
}
